{
    'name': 'MultiShop Theme',
    'description': 'MultiShop website theme',
    'category': 'Theme',
    'sequence': -100,
    'version': '1.0.0.0',
    'depends': ['base', 'website', 'web', 'website_sale', 'website_sale_wishlist', 'website_blog', 'product',
                'website_sale_comparison'],
    'data': [
        'security/ir.model.access.csv',

        'views/topbar.xml',
        'views/shop_main.xml',
        'views/shop_details.xml',
        'views/for_add_field.xml',
        'views/carousel_view.xml',
        'views/cart.xml',
        'views/featured_product.xml',
        'views/recently_added.xml',
        'views/offer_product.xml',
        'views/menu.xml',

        # 'views/for_header.xml',
        'views/snippets/snippets.xml',
        'views/snippets/footer_snippets.xml',
        'views/snippets/carousel_snippets.xml',
        'views/snippets/shop_snippets.xml',
        'views/snippets/shop_details_snippets.xml',
        'views/snippets/shopping_cart_snippets.xml',
        'views/snippets/check_out_snippets.xml',
        'views/snippets/featured_product_snippet.xml',
        'views/snippets/categories_snippets.xml',
        'views/snippets/recent_product_snippet.xml',
        'views/snippets/offer_snippet.xml',
        # 'views/footer.xml',

    ],
    'assets': {
        'web.assets_frontend': [

            # JS File
            # 'theme_multishop/static/src/js/for_topbar.js',
            'theme_multishop/static/src/js/categories.js',
            'theme_multishop/static/src/js/carousel.js',
            'theme_multishop/static/src/js/recently_added.js',
            'theme_multishop/static/src/js/featured_product.js',
            'theme_multishop/static/src/js/offer.js',
            'theme_multishop/static/src/js/containerFluide.js',
            # 'theme_multishop/static/src/js/for_filter_color.js',

            'theme_multishop/static/src/xml/snippets/categories_depend.xml',
            'theme_multishop/static/src/xml/snippets/recently_added.xml',
            'theme_multishop/static/src/xml/snippets/featured_product.xml',
            'theme_multishop/static/src/xml/snippets/offer.xml',

            # scss
            'theme_multishop/static/src/scss/style.scss',

            # # scss/bootstrap/scss
            # 'theme_multishop/static/src/scss/bootstrap/scss/_alert.scss',
            # 'theme_multishop/static/src/scss/bootstrap/scss/_badge.scss',
            # 'theme_multishop/static/src/scss/bootstrap/scss/_breadcrumb.scss',
            # 'theme_multishop/static/src/scss/bootstrap/scss/_button-group.scss',
            # 'theme_multishop/static/src/scss/bootstrap/scss/_buttons.scss',
            # 'theme_multishop/static/src/scss/bootstrap/scss/_card.scss',
            # 'theme_multishop/static/src/scss/bootstrap/scss/_carousel.scss',
            # 'theme_multishop/static/src/scss/bootstrap/scss/_close.scss',
            # 'theme_multishop/static/src/scss/bootstrap/scss/_code.scss',
            # 'theme_multishop/static/src/scss/bootstrap/scss/_custom-forms.scss',
            # 'theme_multishop/static/src/scss/bootstrap/scss/_dropdown.scss',
            # 'theme_multishop/static/src/scss/bootstrap/scss/_forms.scss',
            'theme_multishop/static/src/scss/bootstrap/scss/_grid.scss',
            # 'theme_multishop/static/src/scss/bootstrap/scss/_images.scss',
            # 'theme_multishop/static/src/scss/bootstrap/scss/_input-group.scss',
            # 'theme_multishop/static/src/scss/bootstrap/scss/_jumbotron.scss',
            # 'theme_multishop/static/src/scss/bootstrap/scss/_list-group.scss',
            # 'theme_multishop/static/src/scss/bootstrap/scss/_media.scss',
            # 'theme_multishop/static/src/scss/bootstrap/scss/_mixins.scss',
            # 'theme_multishop/static/src/scss/bootstrap/scss/_modal.scss',
            'theme_multishop/static/src/scss/bootstrap/scss/_nav.scss',
            'theme_multishop/static/src/scss/bootstrap/scss/_navbar.scss',
            # 'theme_multishop/static/src/scss/bootstrap/scss/_pagination.scss',
            # 'theme_multishop/static/src/scss/bootstrap/scss/_popover.scss',
            # 'theme_multishop/static/src/scss/bootstrap/scss/_print.scss',
            # 'theme_multishop/static/src/scss/bootstrap/scss/_progress.scss',
            # 'theme_multishop/static/src/scss/bootstrap/scss/_reboot.scss',
            # 'theme_multishop/static/src/scss/bootstrap/scss/_root.scss',
            # 'theme_multishop/static/src/scss/bootstrap/scss/_spinners.scss',
            # 'theme_multishop/static/src/scss/bootstrap/scss/_tables.scss',
            # 'theme_multishop/static/src/scss/bootstrap/scss/_toasts.scss',
            # 'theme_multishop/static/src/scss/bootstrap/scss/_tooltip.scss',
            # 'theme_multishop/static/src/scss/bootstrap/scss/_transitions.scss',
            # 'theme_multishop/static/src/scss/bootstrap/scss/_type.scss',
            # 'theme_multishop/static/src/scss/bootstrap/scss/_utilities.scss',
            # 'theme_multishop/static/src/scss/bootstrap/scss/_variables.scss',
            # 'theme_multishop/static/src/scss/bootstrap/scss/bootstrap.scss',
            # 'theme_multishop/static/src/scss/bootstrap/scss/bootstrap-grid.scss',
            # 'theme_multishop/static/src/scss/bootstrap/scss/bootstrap-reboot.scss',

            # # scss/bootstrap/scss/utilities
            # 'theme_multishop/static/src/scss/bootstrap/scss/utilities/_align.scss',
            # 'theme_multishop/static/src/scss/bootstrap/scss/utilities/_background.scss',
            # 'theme_multishop/static/src/scss/bootstrap/scss/utilities/_borders.scss',
            'theme_multishop/static/src/scss/bootstrap/scss/utilities/_clearfix.scss',
            'theme_multishop/static/src/scss/bootstrap/scss/utilities/_display.scss',
            # 'theme_multishop/static/src/scss/bootstrap/scss/utilities/_embed.scss',
            'theme_multishop/static/src/scss/bootstrap/scss/utilities/_flex.scss',
            # 'theme_multishop/static/src/scss/bootstrap/scss/utilities/_float.scss',
            # 'theme_multishop/static/src/scss/bootstrap/scss/utilities/_interactions.scss',
            # 'theme_multishop/static/src/scss/bootstrap/scss/utilities/_overflow.scss',
            # 'theme_multishop/static/src/scss/bootstrap/scss/utilities/_position.scss',
            # 'theme_multishop/static/src/scss/bootstrap/scss/utilities/_screenreaders.scss',
            # 'theme_multishop/static/src/scss/bootstrap/scss/utilities/_shadows.scss',
            # 'theme_multishop/static/src/scss/bootstrap/scss/utilities/_sizing.scss',
            'theme_multishop/static/src/scss/bootstrap/scss/utilities/_spacing.scss',
            # 'theme_multishop/static/src/scss/bootstrap/scss/utilities/_stretched-link.scss',
            # 'theme_multishop/static/src/scss/bootstrap/scss/utilities/_text.scss',
            # 'theme_multishop/static/src/scss/bootstrap/scss/utilities/_visibility.scss',

            # For mixin
            'theme_multishop/static/src/scss/bootstrap/scss/mixins/_alert.scss',
            'theme_multishop/static/src/scss/bootstrap/scss/mixins/_background-variant.scss',
            'theme_multishop/static/src/scss/bootstrap/scss/mixins/_badge.scss',
            'theme_multishop/static/src/scss/bootstrap/scss/mixins/_border-radius.scss',
            'theme_multishop/static/src/scss/bootstrap/scss/mixins/_box-shadow.scss',
            'theme_multishop/static/src/scss/bootstrap/scss/mixins/_breakpoints.scss',
            'theme_multishop/static/src/scss/bootstrap/scss/mixins/_buttons.scss',
            'theme_multishop/static/src/scss/bootstrap/scss/mixins/_caret.scss',
            'theme_multishop/static/src/scss/bootstrap/scss/mixins/_clearfix.scss',
            'theme_multishop/static/src/scss/bootstrap/scss/mixins/_deprecate.scss',
            'theme_multishop/static/src/scss/bootstrap/scss/mixins/_float.scss',
            'theme_multishop/static/src/scss/bootstrap/scss/mixins/_forms.scss',
            'theme_multishop/static/src/scss/bootstrap/scss/mixins/_gradients.scss',
            'theme_multishop/static/src/scss/bootstrap/scss/mixins/_grid.scss',
            'theme_multishop/static/src/scss/bootstrap/scss/mixins/_grid-framework.scss',
            'theme_multishop/static/src/scss/bootstrap/scss/mixins/_hover.scss',
            'theme_multishop/static/src/scss/bootstrap/scss/mixins/_image.scss',
            'theme_multishop/static/src/scss/bootstrap/scss/mixins/_list-group.scss',
            'theme_multishop/static/src/scss/bootstrap/scss/mixins/_lists.scss',
            'theme_multishop/static/src/scss/bootstrap/scss/mixins/_nav-divider.scss',
            'theme_multishop/static/src/scss/bootstrap/scss/mixins/_pagination.scss',
            'theme_multishop/static/src/scss/bootstrap/scss/mixins/_reset-text.scss',
            'theme_multishop/static/src/scss/bootstrap/scss/mixins/_resize.scss',
            'theme_multishop/static/src/scss/bootstrap/scss/mixins/_screen-reader.scss',
            'theme_multishop/static/src/scss/bootstrap/scss/mixins/_size.scss',
            'theme_multishop/static/src/scss/bootstrap/scss/mixins/_table-row.scss',
            'theme_multishop/static/src/scss/bootstrap/scss/mixins/_text-emphasis.scss',
            'theme_multishop/static/src/scss/bootstrap/scss/mixins/_text-hide.scss',
            'theme_multishop/static/src/scss/bootstrap/scss/mixins/_text-truncate.scss',
            'theme_multishop/static/src/scss/bootstrap/scss/mixins/_transition.scss',
            'theme_multishop/static/src/scss/bootstrap/scss/mixins/_visibility.scss',

            # # For Vendor
            'theme_multishop/static/src/scss/bootstrap/scss/vendor/_rfs.scss',
            #
            # # CSS
            'theme_multishop/static/src/css/bootstrap.css',
            'theme_multishop/static/src/css/bootstrap.min.css',
            'theme_multishop/static/src/css/bootstrap-grid.css',
            'theme_multishop/static/src/css/bootstrap-grid.min.css',
            'theme_multishop/static/src/css/bootstrap-reboot.css',
            'theme_multishop/static/src/css/bootstrap-reboot.min.css',
            'theme_multishop/static/src/css/style.css',
            'theme_multishop/static/src/css/style.min.css',
            'theme_multishop/static/src/css/custom.css',
            'theme_multishop/static/src/css/hello.css',

        ],
        'web._assets_primary_variables': [
            # "theme/static/src/scss/primary_variables.scss",
        ],

    },

    'snippet_lists': {
    },
    'application': False,
    'auto_install': False,
    'license': 'LGPL-3',
}
